db.artists.insert([
  {
    name: "Powerwolf",
    genres: [
      "german metal",
      "metal",
      "power metal",
      "progressive metal",
      "speed metal",
    ],
    href: "https://api.spotify.com/v1/artists/5HFkc3t0HYETL4JeEbDB1v",
    imageUrl:
      "https://i.scdn.co/image/7e5b4efaffeaf013c48307970048ecfb97e068fc?640x640.jpg",
    url: "https://open.spotify.com/artist/5HFkc3t0HYETL4JeEbDB1v",
    events: [
      {
        title: "Powerwolf at Derby, United Kingdom",
        date: "2021-06-02T19:00:00",
        place: "Derby, United Kingdom",
        status: true,
      },
      {
        title: "Greenfield Festival 2021",
        date: "2021-06-03T19:00:00",
        place: "Interlaken, Switzerland",
        status: true,
      },
      {
        title: "Download Festival 2021",
        date: "2021-06-04T19:00:00",
        place: "Castle Donington, United Kingdom",
        status: true,
      },
      {
        title: "Rock am Ring",
        date: "2021-06-11T19:00:00",
        place: "Nürburg, Germany",
        status: true,
      },
      {
        title: "Rock im Park 2021",
        date: "2021-06-11T19:00:00",
        place: "Nürnberg, Germany",
        status: true,
      },
      {
        title: "Rock The Castle",
        date: "2021-06-26T19:00:00",
        place: "Villafranca di Verona, Italy",
        status: true,
      },
      {
        title: "RockHarz Festival 2021",
        date: "2021-07-07T19:00:00",
        place: "Ballenstedt, Germany",
        status: true,
      },
      {
        title: "Powerwolf at Saarbrücken, Germany",
        date: "2021-07-10T18:00:00",
        place: "Saarbrücken, Germany",
        status: true,
      },
      {
        title: "Leyendas Del Rock",
        date: "2021-08-05T19:00:00",
        place: "Villena, Spain",
        status: true,
      },
    ],
  },
  {
    name: "Be'lakor",
    genres: ["australian metal", "melodic death metal"],
    href: "https://api.spotify.com/v1/artists/7qUcsMCdIHrs2LOZlmciQp",
    imageUrl:
      "https://i.scdn.co/image/b0674776d0258eafc3ada4dc89225e4afd4b4865?640x640.jpg",
    url: "https://open.spotify.com/artist/7qUcsMCdIHrs2LOZlmciQp",
    events: [],
  },
  {
    name: "Trivium",
    genres: [
      "alternative metal",
      "melodic metalcore",
      "melodic thrash",
      "metal",
      "metalcore",
      "nu metal",
    ],
    href: "https://api.spotify.com/v1/artists/278ZYwGhdK6QTzE3MFePnP",
    imageUrl:
      "https://i.scdn.co/image/b95e6e51bc8103a6cf97235fdf968f0ebff03236?640x640.jpg",
    url: "https://open.spotify.com/artist/278ZYwGhdK6QTzE3MFePnP",
    events: [
      {
        title: "Knotfest Japan 2021",
        date: "2021-01-10T19:00:00",
        place: "Chiba-city, Japan",
        status: true,
      },
      {
        title: "Trivium at Kota Administrasi Jakarta Selatan, Indonesia",
        date: "2021-01-16T19:00:00",
        place: "Kota Administrasi Jakarta Selatan, Indonesia",
        status: true,
      },
      {
        title: "The Metal Tour Of The Year",
        date: "2021-07-09T19:00:00",
        place: "Clarkston, MI",
        status: true,
      },
      {
        title: "The Metal Tour Of The Year",
        date: "2021-07-11T19:00:00",
        place: "Toronto, ON",
        status: true,
      },
      {
        title: "The Metal Tour Of The Year",
        date: "2021-07-13T19:00:00",
        place: "Burgettstown, PA",
        status: true,
      },
      {
        title: "The Metal Tour Of The Year ",
        date: "2021-07-14T19:00:00",
        place: "Cincinnati, OH",
        status: true,
      },
      {
        title: "Metal Tour Of The Year ",
        date: "2021-07-16T17:00:00",
        place: "Bristow, VA",
        status: true,
      },
      {
        title: "Metal Tour Of The Year",
        date: "2021-07-17T19:00:00",
        place: "Charlotte, NC",
        status: true,
      },
      {
        title: "The Metal Tour Of The Year",
        date: "2021-07-18T19:00:00",
        place: "Raleigh, NC",
        status: true,
      },
      {
        title: "The Metal Tour Of The Year",
        date: "2021-07-20T19:00:00",
        place: "Boston, MA",
        status: true,
      },
      {
        title: "The Metal Tour Of The Year",
        date: "2021-07-21T19:00:00",
        place: "Wantagh, NY",
        status: true,
      },
      {
        title: "The Metal Tour Of The Year",
        date: "2021-07-23T19:00:00",
        place: "Darien Center, NY",
        status: true,
      },
      {
        title: "The Metal Tour Of The Year",
        date: "2021-07-24T19:00:00",
        place: "Holmdel, NJ",
        status: true,
      },
      {
        title: "The Metal Tour Of The Year ",
        date: "2021-07-26T19:00:00",
        place: "Camden, NJ",
        status: true,
      },
      {
        title: "The Metal Tour Of The Year ",
        date: "2021-07-27T19:00:00",
        place: "Cleveland, OH",
        status: true,
      },
      {
        title: "The Metal Tour Of The Year",
        date: "2021-07-28T19:00:00",
        place: "Fishers, IN",
        status: true,
      },
      {
        title: "The Metal Tour Of The Year ",
        date: "2021-07-30T19:00:00",
        place: "Laval, QC",
        status: true,
      },
      {
        title: "The Metal Tour Of The Year ",
        date: "2021-07-31T19:00:00",
        place: "Québec, QC",
        status: true,
      },
      {
        title: "The Metal Tour Of The Year ",
        date: "2021-08-03T19:00:00",
        place: "Green Bay, WI",
        status: true,
      },
      {
        title: "The Metal Tour Of The Year ",
        date: "2021-08-04T19:00:00",
        place: "Minneapolis, MN",
        status: true,
      },
      {
        title: "Trivium at Tinley Park, IL",
        date: "2021-08-06T18:00:00",
        place: "Tinley Park, IL",
        status: true,
      },
      {
        title: "Trivium at Kansas City, MO",
        date: "2021-08-07T18:00:00",
        place: "Kansas City, MO",
        status: true,
      },
      {
        title: "The Metal Tour Of The Year",
        date: "2021-08-08T19:00:00",
        place: "Rogers, AR",
        status: true,
      },
      {
        title: "The Metal Tour Of The Year",
        date: "2021-08-10T19:00:00",
        place: "Maryland Heights, MO",
        status: true,
      },
      {
        title: "The Metal Tour Of The Year ",
        date: "2021-08-11T19:00:00",
        place: "Nashville, TN",
        status: true,
      },
      {
        title: "The Metal Tour Of The Year",
        date: "2021-08-12T19:00:00",
        place: "Alpharetta, GA",
        status: true,
      },
      {
        title: "The Metal Tour Of The Year ",
        date: "2021-08-14T19:00:00",
        place: "West Palm Beach, FL",
        status: true,
      },
      {
        title: "The Metal Tour Of The Year",
        date: "2021-08-18T19:00:00",
        place: "Corpus Christi, TX",
        status: true,
      },
      {
        title: "The Metal Tour Of The Year ",
        date: "2021-08-20T19:00:00",
        place: "Austin, TX",
        status: true,
      },
      {
        title: "The Metal Tour Of The Year ",
        date: "2021-08-21T19:00:00",
        place: "Irving, TX",
        status: true,
      },
      {
        title: "The Metal Tour Of The Year ",
        date: "2021-08-22T19:00:00",
        place: "The Woodlands, TX",
        status: true,
      },
      {
        title: "The Metal Tour Of The Year ",
        date: "2021-08-24T19:00:00",
        place: "El Paso, TX",
        status: true,
      },
      {
        title: "The Metal Tour Of The Year ",
        date: "2021-08-25T19:00:00",
        place: "Albuquerque, NM",
        status: true,
      },
      {
        title: "The Metal Tour Of The Year ",
        date: "2021-08-27T19:00:00",
        place: "Denver, CO",
        status: true,
      },
      {
        title: "The Metal Tour Of The Year ",
        date: "2021-08-29T19:00:00",
        place: "Phoenix, AZ",
        status: true,
      },
      {
        title: "The Metal Tour Of The Year ",
        date: "2021-08-31T19:00:00",
        place: "Reno, NV",
        status: true,
      },
      {
        title: "The Metal Tour Of The Year ",
        date: "2021-09-01T19:00:00",
        place: "Irvine, CA",
        status: true,
      },
      {
        title: "The Metal Tour Of The Year ",
        date: "2021-09-02T19:00:00",
        place: "Concord, CA",
        status: true,
      },
      {
        title: "The Metal Tour Of The Year ",
        date: "2021-09-04T19:00:00",
        place: "Portland, OR",
        status: true,
      },
      {
        title: "The Metal Tour Of The Year ",
        date: "2021-09-05T19:00:00",
        place: "Auburn, WA",
        status: true,
      },
      {
        title: "The Metal Tour Of The Year ",
        date: "2021-09-07T19:00:00",
        place: "Pocatello, ID",
        status: true,
      },
      {
        title: "The Metal Tour Of The Year ",
        date: "2021-09-08T19:00:00",
        place: "West Valley City, UT",
        status: true,
      },
      {
        title: "The Metal Tour Of The Year ",
        date: "2021-09-10T19:00:00",
        place: "Las Vegas, NV",
        status: true,
      },
    ],
  },
  {
    name: "Alcest",
    genres: [
      "atmospheric black metal",
      "blackgaze",
      "french black metal",
      "french metal",
      "french shoegaze",
      "post-black metal",
      "post-metal",
      "shoegaze",
    ],
    href: "https://api.spotify.com/v1/artists/0d5ZwMtCer8dQdOPAgWhe7",
    imageUrl:
      "https://i.scdn.co/image/4c106ec022e645089b4bbf5942312964a3f21171?640x640.jpg",
    url: "https://open.spotify.com/artist/0d5ZwMtCer8dQdOPAgWhe7",
    events: [
      {
        title: "Alcest at Paris, France",
        date: "2020-12-19T18:30:00",
        place: "Paris, France",
        status: true,
      },
    ],
  },
  {
    name: "Dream Theater",
    genres: [
      "metal",
      "neo classical metal",
      "power metal",
      "progressive metal",
      "progressive rock",
      "rock",
    ],
    href: "https://api.spotify.com/v1/artists/2aaLAng2L2aWD2FClzwiep",
    imageUrl:
      "https://i.scdn.co/image/7a45b5792bde17098a0037509018f7f5bbfc6a99?640x640.jpg",
    url: "https://open.spotify.com/artist/2aaLAng2L2aWD2FClzwiep",
    events: [
      {
        title: "Dream Theater at 日本江東区",
        date: "2020-10-22T19:00:00",
        place: "日本江東区",
        status: true,
      },
      {
        title: "Dream Theater at 日本大阪市",
        date: "2020-10-23T19:00:00",
        place: "日本大阪市",
        status: true,
      },
      {
        title: "Dream Theater at 日本名古屋市",
        date: "2020-10-26T19:00:00",
        place: "日本名古屋市",
        status: true,
      },
      {
        title: "Dream Theater at Sydney, Australia",
        date: "2020-11-01T20:00:00",
        place: "Sydney, Australia",
        status: true,
      },
      {
        title: "Dream Theater at Brisbane, Australia",
        date: "2020-11-02T20:00:00",
        place: "Brisbane, Australia",
        status: true,
      },
      {
        title: "Dream Theater at Karramomous North, Australia",
        date: "2020-11-04T19:30:00",
        place: "Karramomous North, Australia",
        status: true,
      },
      {
        title: "Dream Theater at Hindmarsh, Australia",
        date: "2020-11-05T19:30:00",
        place: "Hindmarsh, Australia",
        status: true,
      },
    ],
  },
  {
    name: "Opeth",
    genres: [
      "alternative metal",
      "death metal",
      "metal",
      "progressive metal",
      "rock",
      "swedish metal",
      "swedish progressive metal",
    ],
    href: "https://api.spotify.com/v1/artists/0ybFZ2Ab08V8hueghSXm6E",
    imageUrl:
      "https://i.scdn.co/image/f03a78ab9215535590b5634dd9e75fb057782f02?640x640.jpg",
    url: "https://open.spotify.com/artist/0ybFZ2Ab08V8hueghSXm6E",
    events: [
      {
        title: "Summer Breeze (POSTPONED TO 2021)",
        date: "2020-08-12T19:00:00",
        place: "Dinkelsbühl, Germany",
        status: true,
      },
      {
        title: "Opeth at Tallinn, Estonia",
        date: "2021-03-10T19:00:00",
        place: "Tallinn, Estonia",
        status: true,
      },
      {
        title: "Opeth at Riga, Latvia",
        date: "2021-03-11T19:00:00",
        place: "Riga, Latvia",
        status: true,
      },
      {
        title: "Opeth at Warsaw, Poland",
        date: "2021-03-12T19:00:00",
        place: "Warsaw, Poland",
        status: true,
      },
      {
        title: "Opeth at Wrocław, Poland",
        date: "2021-03-13T19:00:00",
        place: "Wrocław, Poland",
        status: true,
      },
      {
        title: "Opeth at Karlín, Czechia",
        date: "2021-03-15T19:30:00",
        place: "Karlín, Czechia",
        status: true,
      },
      {
        title: "Opeth at Vienna, Austria",
        date: "2021-03-16T19:00:00",
        place: "Vienna, Austria",
        status: true,
      },
      {
        title: "Opeth at Budapest, Hungary",
        date: "2021-03-17T19:00:00",
        place: "Budapest, Hungary",
        status: true,
      },
      {
        title: "Opeth at Bucharest, Romania",
        date: "2021-03-19T19:00:00",
        place: "Bucharest, Romania",
        status: true,
      },
      {
        title: "Opeth at Sofia, Bulgaria",
        date: "2021-03-20T19:00:00",
        place: "Sofia, Bulgaria",
        status: true,
      },
      {
        title: "Opeth at Zagreb, Croatia",
        date: "2021-03-22T19:00:00",
        place: "Zagreb, Croatia",
        status: true,
      },
      {
        title: "Opeth at Milan, Italy",
        date: "2021-03-23T19:00:00",
        place: "Milan, Italy",
        status: true,
      },
      {
        title: "Opeth at Zapote, Costa Rica",
        date: "2021-04-27T19:00:00",
        place: "Zapote, Costa Rica",
        status: false,
      },
      {
        title: "Opeth at Bogotá, Colombia",
        date: "2021-04-29T19:00:00",
        place: "Bogotá, Colombia",
        status: true,
      },
      {
        title: "Opeth at Santiago, Chile",
        date: "2021-05-01T19:00:00",
        place: "Santiago, Chile",
        status: true,
      },
      {
        title: "Opeth at Don Bosco, Argentina",
        date: "2021-05-04T19:00:00",
        place: "Don Bosco, Argentina",
        status: true,
      },
      {
        title: "Opeth at São Paulo, Brazil",
        date: "2021-05-06T19:00:00",
        place: "São Paulo, Brazil",
        status: true,
      },
      {
        title: "Copenhell (Performance Date TBA)",
        date: "2021-06-16T19:00:00",
        place: "Copenhagen, Denmark",
        status: true,
      },
      {
        title: "Hellfest Open Air",
        date: "2021-06-18T19:00:00",
        place: "Clisson, France",
        status: true,
      },
      {
        title: "Leyendas del Rock (Performance Date TBA)",
        date: "2021-08-05T19:00:00",
        place: "Villena, Spain",
        status: true,
      },
      {
        title: "Beyond The Gates Festival",
        date: "2021-08-07T18:00:00",
        place: "Bergen, Norway",
        status: false,
      },
      {
        title: "ArcTanGent (Performance Date TBA)",
        date: "2021-08-19T20:00:00",
        place: "Compton Martin, United Kingdom",
        status: true,
      },
    ],
  },
  {
    name: "Heaven Shall Burn",
    genres: [
      "german metalcore",
      "melodic death metal",
      "melodic metalcore",
      "metalcore",
    ],
    href: "https://api.spotify.com/v1/artists/4sy5qWfwUwpGYBnCKnwfcW",
    imageUrl:
      "https://i.scdn.co/image/3af77a4d4a9d7a59cc231c46d2373019709d2fd0?640x640.jpg",
    url: "https://open.spotify.com/artist/4sy5qWfwUwpGYBnCKnwfcW",
    events: [
      {
        title: "Heaven Shall Burn at Clisson, France",
        date: "2021-06-19T00:00:00",
        place: "Clisson, France",
        status: true,
      },
      {
        title: "Full Force Festival 2021",
        date: "2021-06-25T19:00:00",
        place: "Gräfenhainichen, Germany",
        status: false,
      },
      {
        title: "Masters of Rock 2021",
        date: "2021-07-08T19:00:00",
        place: "Vizovice, Czechia",
        status: true,
      },
      {
        title: "Gefle Metal Festival 2021",
        date: "2021-07-15T19:00:00",
        place: "Gävle, Sweden",
        status: true,
      },
      {
        title: "Heaven Shall Burn at Eindhoven, Netherlands",
        date: "2021-08-20T15:00:00",
        place: "Eindhoven, Netherlands",
        status: true,
      },
      {
        title: "Heaven Shall Burn at Eindhoven, Netherlands",
        date: "2021-08-21T15:00:00",
        place: "Eindhoven, Netherlands",
        status: true,
      },
    ],
  },
  {
    name: "Periphery",
    genres: [
      "djent",
      "melodic metalcore",
      "progressive metal",
      "progressive metalcore",
    ],
    href: "https://api.spotify.com/v1/artists/6d24kC5fxHFOSEAmjQPPhc",
    imageUrl:
      "https://i.scdn.co/image/c1ed9076e037cd61de521d397ee7d1b0902ea4ae?640x640.jpg",
    url: "https://open.spotify.com/artist/6d24kC5fxHFOSEAmjQPPhc",
    events: [],
  },
  {
    name: "August Burns Red",
    genres: [
      "christian metal",
      "christian metalcore",
      "deathcore",
      "melodic metalcore",
      "metalcore",
      "screamo",
    ],
    href: "https://api.spotify.com/v1/artists/5p9CTsn5ueGU4oScNX1axu",
    imageUrl:
      "https://i.scdn.co/image/1c1bd2bdd10389a2cbfceac09c8c0c2d091dc5d0?640x640.jpg",
    url: "https://open.spotify.com/artist/5p9CTsn5ueGU4oScNX1axu",
    events: [],
  },
  {
    name: "Eluveitie",
    genres: [
      "bow pop",
      "celtic metal",
      "celtic rock",
      "folk metal",
      "hurdy-gurdy",
      "melodic death metal",
      "power metal",
      "swiss metal",
    ],
    href: "https://api.spotify.com/v1/artists/5X0N2k3qMnI8kSrGJT3kfT",
    imageUrl:
      "https://i.scdn.co/image/394e7c9e21fa0f94633424c633ef5d4f69d713f5?640x640.jpg",
    url: "https://open.spotify.com/artist/5X0N2k3qMnI8kSrGJT3kfT",
    events: [
      {
        title: "Metalfest Open Air 2020",
        date: "2021-06-03T19:00:00",
        place: "Pilsen, Czechia",
        status: true,
      },
      {
        title: "Eluveitie at Helsinki, Finland",
        date: "2021-07-02T19:00:00",
        place: "Helsinki, Finland",
        status: true,
      },
    ],
  },
  {
    name: "Ensiferum",
    genres: [
      "finnish metal",
      "folk metal",
      "melodic death metal",
      "metal",
      "power metal",
      "viking metal",
    ],
    href: "https://api.spotify.com/v1/artists/0krXCIkthz13P8o0v2tksH",
    imageUrl:
      "https://i.scdn.co/image/499848717fd67aadb4b55ffe37d5d76f6cf65b49?640x640.jpg",
    url: "https://open.spotify.com/artist/0krXCIkthz13P8o0v2tksH",
    events: [
      {
        title: "*CANCELLED* Summer Breeze Open Air",
        date: "2020-08-14T19:00:00",
        place: "Dinkelsbühl, Germany",
        status: true,
      },
      {
        title: "Ensiferum at Helsinki, Finland",
        date: "2020-09-02T19:00:00",
        place: "Helsinki, Finland",
        status: true,
      },
      {
        title: "HRH Vikings",
        date: "2020-11-28T19:00:00",
        place: "Sheffield, United Kingdom",
        status: true,
      },
      {
        title: "Vienna Metal Meeting",
        date: "2021-05-22T19:00:00",
        place: "Vienna, Austria",
        status: true,
      },
      {
        title: "Metalfest Open Air",
        date: "2021-06-03T19:00:00",
        place: "Okres Plzeň-město, Czechia",
        status: true,
      },
      {
        title: "Tons of Rock",
        date: "2021-06-26T19:00:00",
        place: "Oslo, Norway",
        status: true,
      },
      {
        title: " Dokk'em Open Air ",
        date: "2021-07-01T19:00:00",
        place: "Dokkum, Netherlands",
        status: true,
      },
      {
        title: "Rockharz Open Air 2021",
        date: "2021-07-07T19:00:00",
        place: "Ballenstedt, Germany",
        status: true,
      },
    ],
  },
  {
    name: "Avantasia",
    genres: [
      "german metal",
      "melodic metal",
      "metal",
      "neo classical metal",
      "opera metal",
      "power metal",
      "progressive metal",
      "speed metal",
      "symphonic metal",
    ],
    href: "https://api.spotify.com/v1/artists/1Ih0fEQQsy9EeAJbYEeQRa",
    imageUrl:
      "https://i.scdn.co/image/4fdbba3e73123f7933b8dfa3323e432a25958188?640x640.jpg",
    url: "https://open.spotify.com/artist/1Ih0fEQQsy9EeAJbYEeQRa",
    events: [
      {
        title: "Avantasia at Coburg, Germany",
        date: "2020-08-21T19:30:00",
        place: "Coburg, Germany",
        status: true,
      },
      {
        title: "Avantasia at Villafranca di Verona, Italy",
        date: "2021-07-03T14:15:00",
        place: "Villafranca di Verona, Italy",
        status: true,
      },
      {
        title: "Avantasia at Gävle, Sweden",
        date: "2021-07-14T20:00:00",
        place: "Gävle, Sweden",
        status: true,
      },
      {
        title: "Avantasia at Ludwigsburg, Germany",
        date: "2021-08-05T19:30:00",
        place: "Ludwigsburg, Germany",
        status: true,
      },
      {
        title: "Avantasia at Coburg, Germany",
        date: "2021-08-27T19:30:00",
        place: "Coburg, Germany",
        status: true,
      },
    ],
  },
  {
    name: "Amon Amarth",
    genres: [
      "alternative metal",
      "death metal",
      "melodic death metal",
      "metal",
      "power metal",
      "swedish death metal",
      "swedish metal",
      "tolkien metal",
      "viking metal",
    ],
    href: "https://api.spotify.com/v1/artists/3pulcT2wt7FEG10lQlqDJL",
    imageUrl:
      "https://i.scdn.co/image/87c56a727b4dbb8355761f417f39462abfc095ae?640x640.jpg",
    url: "https://open.spotify.com/artist/3pulcT2wt7FEG10lQlqDJL",
    events: [
      {
        title: "Amon Amarth at Vizovice, Czechia",
        date: "2021-07-08T19:00:00",
        place: "Vizovice, Czechia",
        status: true,
      },
    ],
  },
  {
    name: "Dark Tranquillity",
    genres: [
      "death metal",
      "gothenburg metal",
      "melodic death metal",
      "metal",
      "progressive metal",
      "swedish death metal",
      "swedish metal",
    ],
    href: "https://api.spotify.com/v1/artists/5EHvXKnNz78jkAVgTQLQ5O",
    imageUrl:
      "https://i.scdn.co/image/c25994b0beba4f38e1ae37c975b2a39f273cda4a?640x640.jpg",
    url: "https://open.spotify.com/artist/5EHvXKnNz78jkAVgTQLQ5O",
    events: [],
  },
  {
    name: "Insomnium",
    genres: [
      "finnish death metal",
      "finnish metal",
      "melodic death metal",
      "metal",
    ],
    href: "https://api.spotify.com/v1/artists/3uIgLG971oRM5fe6v8lvQS",
    imageUrl:
      "https://i.scdn.co/image/4a3d5b1307a13320b31adaa71ea459e68d9d6fe3?640x640.jpg",
    url: "https://open.spotify.com/artist/3uIgLG971oRM5fe6v8lvQS",
    events: [
      {
        title: "Insomnium at Kotka, Finland",
        date: "2020-08-14T20:00:00",
        place: "Kotka, Finland",
        status: false,
      },
      {
        title: "Insomnium at Çankaya, Turkey",
        date: "2020-09-11T18:30:00",
        place: "Çankaya, Turkey",
        status: false,
      },
      {
        title: "Insomnium at Istanbul, Turkey",
        date: "2020-09-12T18:30:00",
        place: "Istanbul, Turkey",
        status: false,
      },
      {
        title: "Insomnium at Bremen, Germany",
        date: "2020-12-10T20:00:00",
        place: "Bremen, Germany",
        status: true,
      },
      {
        title: "Insomnium at Stockholm, Sweden",
        date: "2020-12-12T19:30:00",
        place: "Stockholm, Sweden",
        status: true,
      },
      {
        title: "Insomnium at Oslo, Norway",
        date: "2020-12-13T19:30:00",
        place: "Oslo, Norway",
        status: true,
      },
      {
        title: "Insomnium at Göteborg, Sweden",
        date: "2020-12-14T19:30:00",
        place: "Göteborg, Sweden",
        status: true,
      },
      {
        title: "Insomnium at Copenhagen, Denmark",
        date: "2020-12-15T19:30:00",
        place: "Copenhagen, Denmark",
        status: true,
      },
      {
        title: "Insomnium at Hamburg, Germany",
        date: "2020-12-16T20:00:00",
        place: "Hamburg, Germany",
        status: true,
      },
      {
        title: "Insomnium at Stuttgart, Germany",
        date: "2020-12-17T20:00:00",
        place: "Stuttgart, Germany",
        status: true,
      },
      {
        title: "Insomnium at Mannheim, Germany",
        date: "2020-12-18T20:00:00",
        place: "Mannheim, Germany",
        status: true,
      },
      {
        title: "Insomnium at München, Germany",
        date: "2020-12-19T20:00:00",
        place: "München, Germany",
        status: true,
      },
      {
        title: "Insomnium at Aschaffenburg, Germany",
        date: "2020-12-20T19:00:00",
        place: "Aschaffenburg, Germany",
        status: true,
      },
      {
        title: "Insomnium at Berlin, Germany",
        date: "2020-12-21T20:00:00",
        place: "Berlin, Germany",
        status: true,
      },
      {
        title: "Insomnium at Tel Aviv, Israel",
        date: "2021-01-20T19:00:00",
        place: "Tel Aviv, Israel",
        status: true,
      },
      {
        title: "Insomnium at Dallas, TX",
        date: "2021-04-09T20:00:00",
        place: "Dallas, TX",
        status: true,
      },
      {
        title: "Insomnium at Denver, CO",
        date: "2021-06-13T19:00:00",
        place: "Denver, CO",
        status: false,
      },
      {
        title: "Insomnium at Dallas, TX",
        date: "2021-06-15T20:00:00",
        place: "Dallas, TX",
        status: true,
      },
      {
        title: "Insomnium at Helsinki, Finland",
        date: "2021-07-02T19:00:00",
        place: "Helsinki, Finland",
        status: true,
      },
    ],
  },
  {
    name: "In Flames",
    genres: [
      "alternative metal",
      "gothenburg metal",
      "melodic death metal",
      "melodic metalcore",
      "metal",
      "nu metal",
      "swedish death metal",
      "swedish metal",
    ],
    href: "https://api.spotify.com/v1/artists/57ylwQTnFnIhJh4nu4rxCs",
    imageUrl:
      "https://i.scdn.co/image/4b3a112727ca71a0504999a10a38a0dac7e7264c?640x640.jpg",
    url: "https://open.spotify.com/artist/57ylwQTnFnIhJh4nu4rxCs",
    events: [
      {
        title: "In Flames at Liverpool, United Kingdom",
        date: "2021-04-26T19:00:00",
        place: "Liverpool, United Kingdom",
        status: true,
      },
      {
        title: "In Flames at Clarkston, MI",
        date: "2021-07-09T18:00:00",
        place: "Clarkston, MI",
        status: true,
      },
      {
        title: "In Flames at Toronto, ON",
        date: "2021-07-11T18:00:00",
        place: "Toronto, ON",
        status: true,
      },
      {
        title: "In Flames at Burgettstown, PA",
        date: "2021-07-13T18:00:00",
        place: "Burgettstown, PA",
        status: true,
      },
      {
        title: "In Flames at Cincinnati, OH",
        date: "2021-07-14T18:00:00",
        place: "Cincinnati, OH",
        status: true,
      },
      {
        title: "In Flames at Bristow, VA",
        date: "2021-07-16T18:00:00",
        place: "Bristow, VA",
        status: true,
      },
      {
        title: "In Flames at Charlotte, NC",
        date: "2021-07-17T18:00:00",
        place: "Charlotte, NC",
        status: true,
      },
      {
        title: "In Flames at Raleigh, NC",
        date: "2021-07-18T17:30:00",
        place: "Raleigh, NC",
        status: true,
      },
      {
        title: "In Flames at Boston, MA",
        date: "2021-07-20T18:00:00",
        place: "Boston, MA",
        status: true,
      },
      {
        title: "In Flames at Wantagh, NY",
        date: "2021-07-21T18:00:00",
        place: "Wantagh, NY",
        status: true,
      },
      {
        title: "In Flames at Darien Center, NY",
        date: "2021-07-23T18:00:00",
        place: "Darien Center, NY",
        status: true,
      },
      {
        title: "In Flames at Holmdel, NJ",
        date: "2021-07-24T18:00:00",
        place: "Holmdel, NJ",
        status: true,
      },
      {
        title: "In Flames at Camden, NJ",
        date: "2021-07-26T18:00:00",
        place: "Camden, NJ",
        status: true,
      },
      {
        title: "In Flames at Cleveland, OH",
        date: "2021-07-27T18:00:00",
        place: "Cleveland, OH",
        status: true,
      },
      {
        title: "In Flames at Noblesville, IN",
        date: "2021-07-28T18:00:00",
        place: "Noblesville, IN",
        status: true,
      },
      {
        title: "In Flames at Laval, QC",
        date: "2021-07-30T18:00:00",
        place: "Laval, QC",
        status: true,
      },
      {
        title: "In Flames at Ville de Québec, QC",
        date: "2021-07-31T18:00:00",
        place: "Ville de Québec, QC",
        status: true,
      },
      {
        title: "In Flames at Green Bay, WI",
        date: "2021-08-03T18:00:00",
        place: "Green Bay, WI",
        status: true,
      },
      {
        title: "In Flames at Minneapolis, MN",
        date: "2021-08-04T18:00:00",
        place: "Minneapolis, MN",
        status: true,
      },
      {
        title: "In Flames at Tinley Park, IL",
        date: "2021-08-06T18:00:00",
        place: "Tinley Park, IL",
        status: true,
      },
      {
        title: "In Flames at Kansas City, MO",
        date: "2021-08-07T18:00:00",
        place: "Kansas City, MO",
        status: true,
      },
      {
        title: "In Flames at Rogers, AR",
        date: "2021-08-08T18:00:00",
        place: "Rogers, AR",
        status: true,
      },
      {
        title: "In Flames at Maryland Heights, MO",
        date: "2021-08-10T18:00:00",
        place: "Maryland Heights, MO",
        status: true,
      },
      {
        title: "In Flames at Nashville, TN",
        date: "2021-08-11T18:00:00",
        place: "Nashville, TN",
        status: true,
      },
      {
        title: "In Flames at Alpharetta, GA",
        date: "2021-08-12T18:00:00",
        place: "Alpharetta, GA",
        status: true,
      },
      {
        title: "In Flames at West Palm Beach, FL",
        date: "2021-08-14T18:00:00",
        place: "West Palm Beach, FL",
        status: true,
      },
      {
        title: "In Flames at Corpus Christi, TX",
        date: "2021-08-18T18:00:00",
        place: "Corpus Christi, TX",
        status: true,
      },
      {
        title: "In Flames at Austin, TX",
        date: "2021-08-20T18:00:00",
        place: "Austin, TX",
        status: true,
      },
      {
        title: "In Flames at Irving, TX",
        date: "2021-08-21T18:00:00",
        place: "Irving, TX",
        status: true,
      },
      {
        title: "In Flames at The Woodlands, TX",
        date: "2021-08-22T18:30:00",
        place: "The Woodlands, TX",
        status: true,
      },
      {
        title: "In Flames at El Paso, TX",
        date: "2021-08-24T18:00:00",
        place: "El Paso, TX",
        status: true,
      },
      {
        title: "In Flames at Albuquerque, NM",
        date: "2021-08-25T18:00:00",
        place: "Albuquerque, NM",
        status: true,
      },
      {
        title: "In Flames at Denver, CO",
        date: "2021-08-27T18:00:00",
        place: "Denver, CO",
        status: true,
      },
      {
        title: "In Flames at Phoenix, AZ",
        date: "2021-08-29T18:00:00",
        place: "Phoenix, AZ",
        status: true,
      },
      {
        title: "In Flames at Reno, NV",
        date: "2021-08-31T20:00:00",
        place: "Reno, NV",
        status: true,
      },
      {
        title: "In Flames at Irvine, CA",
        date: "2021-09-01T18:00:00",
        place: "Irvine, CA",
        status: true,
      },
      {
        title: "In Flames at Concord, CA",
        date: "2021-09-02T18:00:00",
        place: "Concord, CA",
        status: true,
      },
      {
        title: "In Flames at Portland, OR",
        date: "2021-09-04T18:00:00",
        place: "Portland, OR",
        status: true,
      },
      {
        title: "In Flames at Auburn, WA",
        date: "2021-09-05T18:00:00",
        place: "Auburn, WA",
        status: true,
      },
      {
        title: "In Flames at Pocatello, ID",
        date: "2021-09-07T18:00:00",
        place: "Pocatello, ID",
        status: true,
      },
      {
        title: "In Flames at West Valley City, UT",
        date: "2021-09-08T18:00:00",
        place: "West Valley City, UT",
        status: true,
      },
      {
        title: "In Flames at Las Vegas, NV",
        date: "2021-09-10T18:00:00",
        place: "Las Vegas, NV",
        status: true,
      },
    ],
  },
  {
    name: "Dead by April",
    genres: [
      "alternative metal",
      "melodic metalcore",
      "metalcore",
      "swedish metalcore",
      "trancecore",
    ],
    href: "https://api.spotify.com/v1/artists/2otRZcOVNcmdkZ5nEoogy6",
    imageUrl:
      "https://i.scdn.co/image/039ef5a4723ea256fd7b651f64ac8e67881becc5?640x640.jpg",
    url: "https://open.spotify.com/artist/2otRZcOVNcmdkZ5nEoogy6",
    events: [
      {
        title: "Dead by April Headline Show",
        date: "2020-11-03T19:00:00",
        place: "Novosibirsk, Russia",
        status: true,
      },
      {
        title: "Dead by April Headline Show",
        date: "2020-11-05T19:00:00",
        place: "Yekaterinburg, Russia",
        status: true,
      },
      {
        title: "Dead by April Headline Show",
        date: "2020-11-07T19:00:00",
        place: "Samara, Russia",
        status: true,
      },
      {
        title: "Dead by April Headline Show",
        date: "2020-11-09T19:00:00",
        place: "Moscow, Russia",
        status: true,
      },
      {
        title: "Dead by April Headline Show",
        date: "2020-11-11T19:00:00",
        place: "Saint Petersburg, Russia",
        status: true,
      },
      {
        title: "Dead by April Headline Show",
        date: "2020-11-12T19:00:00",
        place: "Kyiv, Ukraine",
        status: true,
      },
      {
        title: "Dead by April at Oulu, Finland",
        date: "2020-11-27T19:00:00",
        place: "Oulu, Finland",
        status: true,
      },
      {
        title: "Dead by April at Tornio, Finland",
        date: "2020-11-28T19:00:00",
        place: "Tornio, Finland",
        status: true,
      },
    ],
  },
  {
    name: "Born Of Osiris",
    genres: [
      "deathcore",
      "djent",
      "melodic deathcore",
      "melodic metalcore",
      "metalcore",
      "progressive metalcore",
    ],
    href: "https://api.spotify.com/v1/artists/4HgqjpBaWctBWVHafQIpRt",
    imageUrl:
      "https://i.scdn.co/image/ebc5d903ec0dc4a8354541ac0d0a1b1e539919d6?640x640.jpg",
    url: "https://open.spotify.com/artist/4HgqjpBaWctBWVHafQIpRt",
    events: [],
  },
  {
    name: "Amorphis",
    genres: [
      "finnish death metal",
      "finnish metal",
      "folk metal",
      "gothic metal",
      "melodic death metal",
      "metal",
      "power metal",
      "progressive doom",
      "progressive metal",
    ],
    href: "https://api.spotify.com/v1/artists/2UOVgpgiNTC6KK0vSC77aD",
    imageUrl:
      "https://i.scdn.co/image/3bf6e694db3481d5a57e64b2df0b375d3c57915f?640x640.jpg",
    url: "https://open.spotify.com/artist/2UOVgpgiNTC6KK0vSC77aD",
    events: [
      {
        title: "Amorphis at Pori, Finland",
        date: "2020-08-22T19:00:00",
        place: "Pori, Finland",
        status: true,
      },
      {
        title: "Amorphis at Helsinki, Finland",
        date: "2020-10-14T19:00:00",
        place: "Helsinki, Finland",
        status: true,
      },
      {
        title: "Amorphis at Helsinki, Finland",
        date: "2020-10-15T19:00:00",
        place: "Helsinki, Finland",
        status: true,
      },
      {
        title: "Amorphis at Helsinki, Finland",
        date: "2020-10-16T19:00:00",
        place: "Helsinki, Finland",
        status: true,
      },
      {
        title: "Amorphis at Oslo, Norway",
        date: "2020-11-16T19:00:00",
        place: "Oslo, Norway",
        status: true,
      },
      {
        title: "Amorphis at Leipzig, Germany",
        date: "2020-11-20T19:00:00",
        place: "Leipzig, Germany",
        status: true,
      },
      {
        title: "Amorphis at Düsseldorf, Germany",
        date: "2020-11-21T19:00:00",
        place: "Düsseldorf, Germany",
        status: true,
      },
      {
        title: "Amorphis at Amsterdam Zuidoost, Netherlands",
        date: "2020-11-23T19:00:00",
        place: "Amsterdam Zuidoost, Netherlands",
        status: false,
      },
      {
        title: "Amorphis at Amsterdam Zuidoost, Netherlands",
        date: "2020-11-24T19:00:00",
        place: "Amsterdam Zuidoost, Netherlands",
        status: false,
      },
      {
        title: "Amorphis at Paris, France",
        date: "2020-11-25T19:00:00",
        place: "Paris, France",
        status: true,
      },
      {
        title: "Amorphis at Antwerpen, Belgium",
        date: "2020-11-26T19:00:00",
        place: "Antwerpen, Belgium",
        status: true,
      },
      {
        title: "Amorphis at Stuttgart, Germany",
        date: "2020-11-28T19:00:00",
        place: "Stuttgart, Germany",
        status: true,
      },
      {
        title: "Amorphis at Esch-Sur-Alzette, Luxembourg",
        date: "2020-11-29T19:00:00",
        place: "Esch-Sur-Alzette, Luxembourg",
        status: true,
      },
      {
        title: "Amorphis at Zürich, Switzerland",
        date: "2020-12-01T19:00:00",
        place: "Zürich, Switzerland",
        status: true,
      },
      {
        title: "Amorphis at Milan, Italy",
        date: "2020-12-03T19:00:00",
        place: "Milan, Italy",
        status: true,
      },
      {
        title: "Amorphis at Munich, Germany",
        date: "2020-12-04T19:00:00",
        place: "Munich, Germany",
        status: true,
      },
      {
        title: "Amorphis at Budapest, Hungary",
        date: "2020-12-07T19:00:00",
        place: "Budapest, Hungary",
        status: true,
      },
      {
        title: "Amorphis at Bamberg, Germany",
        date: "2020-12-09T19:00:00",
        place: "Bamberg, Germany",
        status: true,
      },
      {
        title: "Amorphis at Frankfurt Am Main, Germany",
        date: "2020-12-10T19:00:00",
        place: "Frankfurt Am Main, Germany",
        status: true,
      },
      {
        title: "Amorphis at Wien, Austria",
        date: "2020-12-12T19:00:00",
        place: "Wien, Austria",
        status: true,
      },
      {
        title: "Amorphis at Berlin, Germany",
        date: "2020-12-14T19:00:00",
        place: "Berlin, Germany",
        status: true,
      },
      {
        title: "Amorphis at Cardiff, United Kingdom",
        date: "2020-12-16T19:00:00",
        place: "Cardiff, United Kingdom",
        status: true,
      },
      {
        title: "Amorphis at London, United Kingdom",
        date: "2020-12-18T19:00:00",
        place: "London, United Kingdom",
        status: true,
      },
      {
        title: "Amorphis at Shibuya City, Japan",
        date: "2021-01-18T19:00:00",
        place: "Shibuya City, Japan",
        status: true,
      },
      {
        title: "Amorphis at Maruyamacho, Japan",
        date: "2021-01-19T19:00:00",
        place: "Maruyamacho, Japan",
        status: true,
      },
      {
        title: "Amorphis at Maruyamacho, Japan",
        date: "2021-01-20T19:00:00",
        place: "Maruyamacho, Japan",
        status: true,
      },
      {
        title: "Amorphis at Zamora, Spain",
        date: "2021-06-11T19:00:00",
        place: "Zamora, Spain",
        status: true,
      },
      {
        title: "Masters of Rock 2021",
        date: "2021-07-08T19:00:00",
        place: "Vizovice, Czechia",
        status: true,
      },
      {
        title: "Amorphis at Moscow, Russia",
        date: "2021-08-27T19:00:00",
        place: "Moscow, Russia",
        status: true,
      },
      {
        title: "Amorphis at Saint Petersburg, Russia",
        date: "2021-08-28T19:00:00",
        place: "Saint Petersburg, Russia",
        status: true,
      },
    ],
  },
  {
    name: "Persefone",
    genres: [
      "melodic death metal",
      "musica andorra",
      "progressive metal",
      "symphonic death metal",
      "technical death metal",
    ],
    href: "https://api.spotify.com/v1/artists/4wxyib7wQwVxwKNFBmOhAw",
    imageUrl:
      "https://i.scdn.co/image/5479f9dee3139f3f65c1080db2fb74de9ab4e8ec?640x640.jpg",
    url: "https://open.spotify.com/artist/4wxyib7wQwVxwKNFBmOhAw",
    events: [],
  },
  {
    name: "In Hearts Wake",
    genres: [
      "australian metalcore",
      "melodic metalcore",
      "metalcore",
      "post-screamo",
    ],
    href: "https://api.spotify.com/v1/artists/30BDCIM0IdglDaLzvCYd0N",
    imageUrl:
      "https://i.scdn.co/image/b3228a5fe7fea42c29b874a63cd90f0e69b6e0cc?640x640.jpg",
    url: "https://open.spotify.com/artist/30BDCIM0IdglDaLzvCYd0N",
    events: [
      {
        title: "IN HEARTS WAKE  - KALIYUGA LIVE",
        date: "2020-08-13T20:00:00",
        place: "",
        status: true,
      },
    ],
  },
  {
    name: "Equilibrium",
    genres: [
      "folk metal",
      "german metal",
      "german pagan metal",
      "melodic death metal",
      "melodic metal",
      "neue deutsche harte",
      "power metal",
      "viking metal",
    ],
    href: "https://api.spotify.com/v1/artists/5KvkOKroKLz202ioXfGWR2",
    imageUrl:
      "https://i.scdn.co/image/7654851b9e6b068cce4df39fff17a891e697c0d5?640x640.jpg",
    url: "https://open.spotify.com/artist/5KvkOKroKLz202ioXfGWR2",
    events: [],
  },
  {
    name: "Sonata Arctica",
    genres: [
      "finnish metal",
      "finnish power metal",
      "melodic metal",
      "metal",
      "neo classical metal",
      "power metal",
      "progressive metal",
      "speed metal",
      "symphonic metal",
    ],
    href: "https://api.spotify.com/v1/artists/5YeoQ1L71cXDMpSpqxOjfH",
    imageUrl:
      "https://i.scdn.co/image/a9ce3054c2174b67af523b6d2677ebd53ab1cc18?640x640.jpg",
    url: "https://open.spotify.com/artist/5YeoQ1L71cXDMpSpqxOjfH",
    events: [
      {
        title: "Virtain  Rock Venetsialaiset",
        date: "2020-08-29T17:00:00",
        place: "Virrat, Finland",
        status: true,
      },
      {
        title: "Neljä iltaa",
        date: "2020-09-02T16:00:00",
        place: "Helsinki, Finland",
        status: true,
      },
      {
        title: "Full Metal Cruise 2020 2020",
        date: "2020-09-23T19:00:00",
        place: "Kiel, Germany",
        status: true,
      },
      {
        title: "Sonata Arctica at Belo Horizonte, Brazil",
        date: "2020-11-06T22:00:00",
        place: "Belo Horizonte, Brazil",
        status: true,
      },
      {
        title: "Sonata Arctica at Brasília, Brazil",
        date: "2020-11-07T17:00:00",
        place: "Brasília, Brazil",
        status: true,
      },
      {
        title: "Sonata Arctica at Curitiba, Brazil",
        date: "2020-11-08T18:30:00",
        place: "Curitiba, Brazil",
        status: true,
      },
      {
        title: "Sonata Arctica at Porto Alegre, Brazil",
        date: "2020-11-10T21:00:00",
        place: "Porto Alegre, Brazil",
        status: true,
      },
      {
        title: "Sonata Arctica at Florianópolis, Brazil",
        date: "2020-11-11T19:00:00",
        place: "Florianópolis, Brazil",
        status: true,
      },
      {
        title: "Sonata Arctica at Rio de Janeiro, Brazil",
        date: "2020-11-13T20:00:00",
        place: "Rio de Janeiro, Brazil",
        status: true,
      },
      {
        title: "Sonata Arctica at Limeira, Brazil",
        date: "2020-11-14T22:00:00",
        place: "Limeira, Brazil",
        status: true,
      },
      {
        title: "Sonata Arctica at São Paulo, Brazil",
        date: "2020-11-15T19:00:00",
        place: "São Paulo, Brazil",
        status: true,
      },
      {
        title: "Sonata Arctica at Don Bosco, Argentina",
        date: "2020-11-17T19:00:00",
        place: "Don Bosco, Argentina",
        status: true,
      },
      {
        title: "Sonata Arctica at Santiago, Chile",
        date: "2020-11-19T18:00:00",
        place: "Santiago, Chile",
        status: true,
      },
      {
        title: "Sonata Arctica at Puerto Montt, Chile",
        date: "2020-11-20T19:00:00",
        place: "Puerto Montt, Chile",
        status: true,
      },
      {
        title: "Sonata Arctica at San José, Costa Rica",
        date: "2020-11-22T18:00:00",
        place: "San José, Costa Rica",
        status: false,
      },
      {
        title: "Sonata Arctica at San Salvador, El Salvador",
        date: "2020-11-24T19:00:00",
        place: "San Salvador, El Salvador",
        status: false,
      },
      {
        title: "Sonata Arctica at Guatemala City, Guatemala",
        date: "2020-11-25T19:00:00",
        place: "Guatemala City, Guatemala",
        status: false,
      },
      {
        title: "Sonata Arctica at Tel Aviv, Israel",
        date: "2021-03-17T21:00:00",
        place: "Tel Aviv, Israel",
        status: true,
      },
      {
        title: "Big Gun Festival 2021",
        date: "2021-07-03T16:00:00",
        place: "Pereslavl’-Zalesskiy, Russia",
        status: true,
      },
    ],
  },
  {
    name: "Volumes",
    genres: [
      "djent",
      "melodic metalcore",
      "metalcore",
      "progressive metalcore",
    ],
    href: "https://api.spotify.com/v1/artists/1DgmdsnwOexqTH8ohPCFAU",
    imageUrl:
      "https://i.scdn.co/image/f1d8037fe6d375e311ad83a22902dcd16a75ab05?640x640.jpg",
    url: "https://open.spotify.com/artist/1DgmdsnwOexqTH8ohPCFAU",
    events: [
      {
        title: "Volumes at Mesa, AZ",
        date: "2021-01-27T16:30:00",
        place: "Mesa, AZ",
        status: true,
      },
      {
        title: "Volumes at Pomona, CA",
        date: "2021-01-29T17:30:00",
        place: "Pomona, CA",
        status: true,
      },
      {
        title: "Volumes at Austin, TX",
        date: "2021-02-24T16:00:00",
        place: "Austin, TX",
        status: true,
      },
      {
        title: "Volumes at Dallas, TX",
        date: "2021-02-27T20:00:00",
        place: "Dallas, TX",
        status: true,
      },
    ],
  },
  {
    name: "Ne Obliviscaris",
    genres: [
      "australian metal",
      "avant-garde metal",
      "jazz metal",
      "progressive metal",
    ],
    href: "https://api.spotify.com/v1/artists/5kbidtcpyRRMdAQUnI1BG4",
    imageUrl:
      "https://i.scdn.co/image/50f4e6eea604912f26021e1db9ea4088720db802?640x640.jpg",
    url: "https://open.spotify.com/artist/5kbidtcpyRRMdAQUnI1BG4",
    events: [],
  },
  {
    name: "Metallica",
    genres: [
      "alternative metal",
      "hard rock",
      "metal",
      "old school thrash",
      "rock",
      "thrash metal",
    ],
    href: "https://api.spotify.com/v1/artists/2ye2Wgw4gimLv2eAKyk1NB",
    imageUrl:
      "https://i.scdn.co/image/5a06711d7fc48d5e0e3f9a3274ffed3f0af1bd91?640x640.jpg",
    url: "https://open.spotify.com/artist/2ye2Wgw4gimLv2eAKyk1NB",
    events: [
      {
        title: "Metallica at ",
        date: "2020-08-28T19:00:00",
        place: "",
        status: false,
      },
      {
        title: "Metallica at Southington, CT",
        date: "2020-08-29T20:35:00",
        place: "Southington, CT",
        status: true,
      },
      {
        title: "Metallica at Sacramento, CA",
        date: "2020-10-09T19:00:00",
        place: "Sacramento, CA",
        status: true,
      },
      {
        title: "Metallica at Sacramento, CA",
        date: "2020-10-11T23:00:00",
        place: "Sacramento, CA",
        status: true,
      },
      {
        title: "Metallica at Buenos Aires, Argentina",
        date: "2020-12-04T03:30:00",
        place: "Buenos Aires, Argentina",
        status: false,
      },
      {
        title: "Metallica at Ñuñoa, Chile",
        date: "2020-12-07T19:00:00",
        place: "Ñuñoa, Chile",
        status: true,
      },
      {
        title: "Metallica at Porto Alegre, Brazil",
        date: "2020-12-14T20:00:00",
        place: "Porto Alegre, Brazil",
        status: false,
      },
      {
        title: "Metallica at Curitiba, Brazil",
        date: "2020-12-16T03:30:00",
        place: "Curitiba, Brazil",
        status: false,
      },
    ],
  },
  {
    name: "Asking Alexandria",
    genres: ["metalcore", "trancecore", "uk metalcore"],
    href: "https://api.spotify.com/v1/artists/1caBfBEapzw8z2Qz9q0OaQ",
    imageUrl:
      "https://i.scdn.co/image/310e923a2d780e3ac23df6fcb55ff4a984caa24c?640x640.jpg",
    url: "https://open.spotify.com/artist/1caBfBEapzw8z2Qz9q0OaQ",
    events: [
      {
        title: "Asking Alexandria at Moscow, Russia",
        date: "2020-10-14T19:00:00",
        place: "Moscow, Russia",
        status: true,
      },
      {
        title: "Asking Alexandria at Saint Petersburg, Russia",
        date: "2020-10-15T19:00:00",
        place: "Saint Petersburg, Russia",
        status: true,
      },
      {
        title: "Asking Alexandria at Kyiv, Ukraine",
        date: "2020-10-17T19:00:00",
        place: "Kyiv, Ukraine",
        status: true,
      },
      {
        title: "Asking Alexandria at Glasgow, United Kingdom",
        date: "2020-10-19T19:00:00",
        place: "Glasgow, United Kingdom",
        status: true,
      },
      {
        title: "Asking Alexandria at Manchester, United Kingdom",
        date: "2020-10-20T19:00:00",
        place: "Manchester, United Kingdom",
        status: true,
      },
      {
        title: "Asking Alexandria at Birmingham, United Kingdom",
        date: "2020-10-21T19:00:00",
        place: "Birmingham, United Kingdom",
        status: true,
      },
      {
        title: "Asking Alexandria at London, United Kingdom",
        date: "2020-10-23T19:00:00",
        place: "London, United Kingdom",
        status: true,
      },
      {
        title: "Asking Alexandria at Köln, Germany",
        date: "2020-10-25T19:00:00",
        place: "Köln, Germany",
        status: true,
      },
      {
        title: "Asking Alexandria at Amsterdam, Netherlands",
        date: "2020-10-27T19:00:00",
        place: "Amsterdam, Netherlands",
        status: true,
      },
      {
        title: "Asking Alexandria at Hamburg, Germany",
        date: "2020-10-28T19:00:00",
        place: "Hamburg, Germany",
        status: true,
      },
      {
        title: "Asking Alexandria at Stockholm, Sweden",
        date: "2020-10-30T19:00:00",
        place: "Stockholm, Sweden",
        status: true,
      },
      {
        title: "Asking Alexandria at Oslo, Norway",
        date: "2020-10-31T19:00:00",
        place: "Oslo, Norway",
        status: true,
      },
      {
        title: "Asking Alexandria at Copenhagen, Denmark",
        date: "2020-11-02T19:00:00",
        place: "Copenhagen, Denmark",
        status: true,
      },
      {
        title: "Asking Alexandria at Berlin, Germany",
        date: "2020-11-03T19:00:00",
        place: "Berlin, Germany",
        status: true,
      },
      {
        title: "Asking Alexandria at Warsaw, Poland",
        date: "2020-11-04T19:00:00",
        place: "Warsaw, Poland",
        status: true,
      },
      {
        title: "Asking Alexandria at Karlín, Czechia",
        date: "2020-11-06T19:00:00",
        place: "Karlín, Czechia",
        status: true,
      },
      {
        title: "Asking Alexandria at Vienna, Austria",
        date: "2020-11-07T19:00:00",
        place: "Vienna, Austria",
        status: true,
      },
      {
        title: "Asking Alexandria at Budapest, Hungary",
        date: "2020-11-08T19:00:00",
        place: "Budapest, Hungary",
        status: true,
      },
      {
        title: "Asking Alexandria at Munich, Germany",
        date: "2020-11-10T19:00:00",
        place: "Munich, Germany",
        status: true,
      },
      {
        title: "Asking Alexandria at Milan, Italy",
        date: "2020-11-11T19:00:00",
        place: "Milan, Italy",
        status: true,
      },
      {
        title: "Asking Alexandria at Barcelona, Spain",
        date: "2020-11-13T19:00:00",
        place: "Barcelona, Spain",
        status: true,
      },
      {
        title: "Asking Alexandria at Madrid, Spain",
        date: "2020-11-14T19:00:00",
        place: "Madrid, Spain",
        status: true,
      },
      {
        title: "Asking Alexandria at Paris, France",
        date: "2020-11-17T19:00:00",
        place: "Paris, France",
        status: true,
      },
      {
        title: "Asking Alexandria at Brussels, Belgium",
        date: "2020-11-18T19:00:00",
        place: "Brussels, Belgium",
        status: true,
      },
    ],
  },
  {
    name: "Emil Bulls",
    genres: ["german post-hardcore", "german rock"],
    href: "https://api.spotify.com/v1/artists/1scIUjz7Jbq1mOph50OLQO",
    imageUrl:
      "https://i.scdn.co/image/71c117cef885433c7361b46aa2b123683eedab2a?640x640.jpg",
    url: "https://open.spotify.com/artist/1scIUjz7Jbq1mOph50OLQO",
    events: [],
  },
  {
    name: "Sabaton",
    genres: ["metal", "power metal", "swedish metal", "swedish power metal"],
    href: "https://api.spotify.com/v1/artists/3o2dn2O0FCVsWDFSh8qxgG",
    imageUrl:
      "https://i.scdn.co/image/75edd507eff2593d450c94684c2554f2abd02aed?640x640.jpg",
    url: "https://open.spotify.com/artist/3o2dn2O0FCVsWDFSh8qxgG",
    events: [
      {
        title: "Sabaton at Karlstad, Sweden",
        date: "2021-01-22T20:00:00",
        place: "Karlstad, Sweden",
        status: true,
      },
      {
        title: "Sabaton at Örebro, Sweden",
        date: "2021-01-23T20:00:00",
        place: "Örebro, Sweden",
        status: true,
      },
      {
        title: "Sabaton at Umeå, Sweden",
        date: "2021-01-25T20:00:00",
        place: "Umeå, Sweden",
        status: true,
      },
      {
        title: "Sabaton at Östersund, Sweden",
        date: "2021-01-26T20:00:00",
        place: "Östersund, Sweden",
        status: true,
      },
      {
        title: "Sabaton at Piteå, Sweden",
        date: "2021-01-28T20:00:00",
        place: "Piteå, Sweden",
        status: true,
      },
      {
        title: "Sabaton at Luleå, Sweden",
        date: "2021-01-29T20:00:00",
        place: "Luleå, Sweden",
        status: true,
      },
      {
        title: "Sabaton at Skellefteå, Sweden",
        date: "2021-01-30T20:00:00",
        place: "Skellefteå, Sweden",
        status: true,
      },
      {
        title: "Sabaton at Helsingborg, Sweden",
        date: "2021-02-01T20:00:00",
        place: "Helsingborg, Sweden",
        status: true,
      },
      {
        title: "Sabaton at Malmö, Sweden",
        date: "2021-02-02T20:00:00",
        place: "Malmö, Sweden",
        status: true,
      },
      {
        title: "Sabaton at Halmstad, Sweden",
        date: "2021-02-03T20:00:00",
        place: "Halmstad, Sweden",
        status: true,
      },
      {
        title: "Sabaton at Trollhättan, Sweden",
        date: "2021-02-04T20:00:00",
        place: "Trollhättan, Sweden",
        status: true,
      },
      {
        title: "Sabaton at Ronneby, Sweden",
        date: "2021-02-06T20:00:00",
        place: "Ronneby, Sweden",
        status: true,
      },
      {
        title: "Sabaton at Eskilstuna, Sweden",
        date: "2021-02-07T20:00:00",
        place: "Eskilstuna, Sweden",
        status: true,
      },
      {
        title: "Sabaton at Uppsala, Sweden",
        date: "2021-02-08T20:00:00",
        place: "Uppsala, Sweden",
        status: true,
      },
      {
        title: "Sabaton at Huskvarna, Sweden",
        date: "2021-02-09T20:00:00",
        place: "Huskvarna, Sweden",
        status: true,
      },
      {
        title: "Sabaton at Kristianstad, Sweden",
        date: "2021-02-10T20:00:00",
        place: "Kristianstad, Sweden",
        status: true,
      },
      {
        title: "Sabaton at Älmhult, Sweden",
        date: "2021-02-12T20:00:00",
        place: "Älmhult, Sweden",
        status: true,
      },
      {
        title: "Sabaton at Borås, Sweden",
        date: "2021-02-13T20:00:00",
        place: "Borås, Sweden",
        status: true,
      },
      {
        title: "Sabaton at Linköping, Sweden",
        date: "2021-02-14T20:00:00",
        place: "Linköping, Sweden",
        status: true,
      },
      {
        title: "Sabaton at Norrköping, Sweden",
        date: "2021-02-17T20:00:00",
        place: "Norrköping, Sweden",
        status: true,
      },
      {
        title: "Sabaton at Gävle, Sweden",
        date: "2021-02-18T20:00:00",
        place: "Gävle, Sweden",
        status: true,
      },
      {
        title: "Sabaton at Borlänge, Sweden",
        date: "2021-02-19T20:00:00",
        place: "Borlänge, Sweden",
        status: true,
      },
      {
        title: "Sabaton at Falun, Sweden",
        date: "2021-02-20T20:00:00",
        place: "Falun, Sweden",
        status: true,
      },
      {
        title: "Sabaton at Sundsvall, Sweden",
        date: "2021-02-22T20:00:00",
        place: "Sundsvall, Sweden",
        status: true,
      },
      {
        title: "Sabaton at Mölnlycke, Sweden",
        date: "2021-02-25T20:00:00",
        place: "Mölnlycke, Sweden",
        status: true,
      },
      {
        title: "Sabaton at Karlshamn, Sweden",
        date: "2021-02-26T20:00:00",
        place: "Karlshamn, Sweden",
        status: true,
      },
      {
        title: "Sabaton at Charlotte, NC",
        date: "2021-09-13T19:00:00",
        place: "Charlotte, NC",
        status: true,
      },
      {
        title: "Sabaton at Milwaukee, WI",
        date: "2021-09-22T19:30:00",
        place: "Milwaukee, WI",
        status: true,
      },
      {
        title: "Sabaton at Maryland Heights, MO",
        date: "2021-09-25T19:30:00",
        place: "Maryland Heights, MO",
        status: true,
      },
      {
        title: "Sabaton at Denver, CO",
        date: "2021-09-29T20:00:00",
        place: "Denver, CO",
        status: true,
      },
      {
        title: "Sabaton at Los Angeles, CA",
        date: "2021-10-06T20:00:00",
        place: "Los Angeles, CA",
        status: true,
      },
      {
        title: "Sabaton at Las Vegas, NV",
        date: "2021-10-08T20:00:00",
        place: "Las Vegas, NV",
        status: true,
      },
      {
        title: "Sabaton at Phoenix, AZ",
        date: "2021-10-09T19:30:00",
        place: "Phoenix, AZ",
        status: true,
      },
      {
        title: "Sabaton at San Antonio, TX",
        date: "2021-10-12T20:00:00",
        place: "San Antonio, TX",
        status: true,
      },
      {
        title: "Sabaton at Cedar Park, TX",
        date: "2021-10-13T19:30:00",
        place: "Cedar Park, TX",
        status: true,
      },
      {
        title: "Sabaton at Irving, TX",
        date: "2021-10-15T19:30:00",
        place: "Irving, TX",
        status: true,
      },
      {
        title: "Sabaton at National Harbor, MD",
        date: "2021-10-28T19:30:00",
        place: "National Harbor, MD",
        status: true,
      },
      {
        title: "Sabaton at Ledyard, CT",
        date: "2021-10-30T19:30:00",
        place: "Ledyard, CT",
        status: true,
      },
    ],
  },
  {
    name: "Angra",
    genres: [
      "brazilian metal",
      "brazilian power metal",
      "brazilian progressive metal",
      "latin metal",
      "metal",
      "neo classical metal",
      "power metal",
      "progressive metal",
      "progressive power metal",
      "speed metal",
      "symphonic metal",
    ],
    href: "https://api.spotify.com/v1/artists/7IAXZaLTb6nkJr8RmVPn5y",
    imageUrl:
      "https://i.scdn.co/image/8a4db555cb1c768304fd6bf1a0a8795a3c84d540?640x640.jpg",
    url: "https://open.spotify.com/artist/7IAXZaLTb6nkJr8RmVPn5y",
    events: [],
  },
  {
    name: "Dreamshade",
    genres: [
      "melodic death metal",
      "post-screamo",
      "swedish metalcore",
      "swiss metal",
    ],
    href: "https://api.spotify.com/v1/artists/3A7sZMxNjhJWX7apY1UpQO",
    imageUrl:
      "https://i.scdn.co/image/2c8562b0181a8489195eb5d6019ac851cfce567a?640x640.jpg",
    url: "https://open.spotify.com/artist/3A7sZMxNjhJWX7apY1UpQO",
    events: [],
  },
]);
